class plots:
    units = { 
        "R_im1half":"[cm]",
        "R_ip1half":"[cm]",
        "<D>":"[g/cm^3]",
        "D_max":"[g/cm^3]""" ,
        "D_min":"[g/cm^3]",
        "U_ave_im1half":"[cm/s]",
        "U_max_im1half":"[cm/s]",
        "U_min_im1half":"[cm/s]",
        "U0":"[cm/s]",
        "V_ave":"[cm/s]",
        "V_max":"[cm/s]",
        "V_min":"[cm/s]",
        "W_ave":"[cm/s]",
        "W_max":"[cm/s]",
        "W_min":"[cm/s]",
        "Q":"[dynes/cm^2]",
        "Q_max":"[dynes/cm^2]",
        "Q_min":"[dynes/cm^2]",
        "E_ave":"[erg/g]",
        "E_max":"[erg/g]",
        "E_min":"[erg/g]",
        "T_ave":"[K]",
        "T_max":"[K]",
        "T_min":"[K]",
        "Kap_ave":"[cm^2/g]",
        "Kap_min":"[cm^2/g]",
        "Kap_max":"[cm^2/g]",
        "L_rd_im1half":"[L_sun]",
        "L_cv_im1half":"[L_sun]",
        "F_cv_ave":"[L_sun/cm^2]",
        "F_cv_max":"[L_sun/cm^2]",
        "F_cv_min":"[L_sun/cm^2]",
        "KEP":"[ergs]",
        "KETot":"[ergs]",
        "P_ave":"[dynes/cm^2]",
        "P_min":"[dynes/cm^2]",
        "P_max":"[dynes/cm^2]",
        "Gam_ave":"[na]",
        "Gam_min":"[na]",
        "Gam_max":"[na]",
        "C_ave":"[cm/s]",
        "C_max":"[cm/s]",
        "C_min":"[cm/s]"
    }
    
    colors = ['b', 'g', 'r', 'c', 'm', 'y', 'k', 'w']
    markers = ['.', '*', 'v', 'P', '+', 'x']